trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End
- group: RPi4

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/build'
    artifact: 'compiled front-end'
    publishLocation: 'pipeline'
  displayName: 'Publish Build as Artifact'
