trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End
- group: RPi4  # Include the RPi4 variable group

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- bash: |
    echo "Setting up SSH key..."
    mkdir -p ~/.ssh
    echo "$(RPI_PRIVATE_KEY)" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -6 -H $(RPI_HOST) >> ~/.ssh/known_hosts
    echo "SSH Setup complete."
  displayName: 'Setup SSH Key'
  env:
    RPI_PRIVATE_KEY: $(RPI_PRIVATE_KEY)

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'My_RPi_Connection' 
    sourceFolder: '$(Build.SourcesDirectory)/build'
    targetFolder: '$(RPI_BUILD_DIR)'