# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- task: DownloadSecureFile@1
  name: downloadKey
  displayName: 'Download SSH Key'
  inputs:
    secureFile: 'id_rsa'

- bash: |
    echo "Setting up SSH key..."
    mkdir -p $(System.DefaultWorkingDirectory)/.ssh
    mv $(downloadKey.secureFilePath) $(System.DefaultWorkingDirectory)/.ssh/id_rsa
    chmod 600 $(System.DefaultWorkingDirectory)/.ssh/id_rsa
    echo "Adding host to known hosts..."
    ssh-keyscan -6 -H 2a01:4b00:d10f:5300:da3a:ddff:fe2e:d4d9 >> $(System.DefaultWorkingDirectory)/.ssh/known_hosts
    echo "SSH Setup complete."
  displayName: 'Setup SSH Key'

- bash: |
    echo "Copying build folder to remote machine..."
    scp -i $(System.DefaultWorkingDirectory)/.ssh/id_rsa -r $(Build.SourcesDirectory)/build pi@2a01:4b00:d10f:5300:da3a:ddff:fe2e:d4d9:/var/www/borderbales/
  displayName: 'Copy Build Folder'
