trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End
- group: Docker
- name: imageName
  value: '$(DockerRepo)/$(FrontEndContainer):$(Build.BuildId)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- script: |
    echo "Image Name: $(imageName)"
    docker build -t $(imageName) .
  displayName: 'Build Docker image for front-end'

- script: |
    echo $(DockerPassword) | docker login -u $(DockerUsername) --password-stdin
    docker push $(imageName)
  displayName: 'Push Docker image to Docker Hub'
  env:
    DockerUsername: $(DockerUsername)
    DockerPassword: $(DockerPassword)
