trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End
- group: Docker
- name: imageName
  value: '$(DockerRepo)/$(FrontEndContainer)'
- name: dockerHubServiceConnection
  value: 'Docker Hub'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- task: Docker@2
  displayName: 'Build Docker image for front-end'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: $(dockerHubServiceConnection)
    repository: $(DockerUsername)/$(imageName)
    command: 'push'
    tags: |
      $(Build.BuildId)
