# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Front-End
- group: RPi4

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    REACT_APP_API_URL: $(REACT_APP_API_URL)
    REACT_APP_AUTH_COOKIE: $(REACT_APP_AUTH_COOKIE)
  displayName: 'npm run build'

- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'id_rsa'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(RPI_HOST)'
    sshKeySecureFile: '$(sshKey.secureFilePath)'

- task: SSH@0
  inputs:
    sshEndpoint: 'My_RPi_Connection'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'My_RPi_Connection' 
    sourceFolder: '$(Build.SourcesDirectory)/build'
    targetFolder: '$(RPI_USERNAME)@$(RPI_HOST):$(RPI_BUILD_DIR)'